### ISSUE TITLE
Configure and run Logback (not) automatically

### ISSUE THREAD

**Issue by auguwu** [charted-dev/charted#86]
Since migrating to Logback 1.4, there is issues with logging, i.e, not printing to stdout, so this should aim to run Logback BEFORE anything else (i.e, when hooks (uncaught thread exceptions/runtime hooks) are applied) in the [Bootstrap.kt](https://github.com/charted-dev/charted/blob/00b174fcda2f3e839e5ebd4bd2c4b0615c0977f7/server/src/main/kotlin/org/noelware/charted/server/Bootstrap.kt) file.

And, it causes more issues when we want to add more appenders and such. So, this will deprecate the `config/logback.properties` configuration file and Logback will start programmatically using [SPI](https://docs.oracle.com/javase/tutorial/ext/basics/spi.html).

## Configuration
Since we have pieces that are configurable to Logback, we will have to load the configuration before the runtime/thread exception hooks, which will present a `LogbackConfig` data class:

### Kotlin DSL
```kt
logback {
   // Enables the file appender for appending logs to files.
   enable<FileAppender>()

   // Enables Logstash for the Elastic Stack
   enable<LogstashAppender> {
       type = LogstashAppender.Connectors.TCP
       endpoint = "localhost:4040"
    }

    // Enables the appender for Sentry, which will use the DSN configured from `sentry_dsn` by default
    // you can add the DSN with the DSN parameter in `enable<SentryAppender>`
    enable<SentryAppender>()

    // Uses the JSON layout instead of the default console formatter
    json = true

    // The timezone for the time when printed to console
    timezone = "Etc/Utc".parseIntoTimezone()
}
```

### YAML
```yaml
logback:
  json: true

  # This will be overridden by the `TZ` environment variable, defaults to UTC.
  timezone: Etc/Utc
  appenders:
    - type: file
    - type: logstash
      options:
        type: TCP
        endpoint: localhost:4040
```
